import { Timestamp } from 'firebase/firestore';

// Defines the structure of a transaction record
export interface Transaction {
  id: string; // Unique identifier for the transaction
  contactId: string; // ID of the contact associated with the transaction
  amount: number; // The amount of the transaction
  purpose: string; // A brief description of the transaction
  type: 'lent' | 'received'; // The type of transaction (e.g., money received or money spent)
  date: Timestamp; // The date of the transaction
  createdAt: Timestamp; // The timestamp when the transaction was created
  userId: string; // The ID of the user who created the transaction
}

// Defines the data structure for the transaction form, excluding fields generated by the system
export type TransactionFormData = Omit<Transaction, 'id' | 'createdAt' | 'userId'>;
